language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

env:
  - DB=sqlite

sqlite:
  adapter: sqlite3
  database: ':memory:'
  timeout: 500

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

before_script:
  - cp .env.testing .env
  - composer test --no-interaction

script:
  - vendor/bin/phpunit